version: '3.3'
services:
  web:
    build: .
    container_name: prlmos
    ports:
      - "5000:5000"
    volumes:
      - .:/prlmos_app
    links:
      - 'mongodb'
    depends_on:
      - 'mongodb'
    environment:
      - MONGODB_PORT_27017_TCP_ADDR=172.17.0.1
      - MONGODB_PORT_27017_TCP_PORT=27017
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="password"
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod #--smallfiles --logpath=/dev/null
